### ISSUE TITLE
make working FrontEnd

### ISSUE THREAD

**Issue by phoenix-aditya** [phoenix-aditya/GeekStat#2]
**Tasks for FrontEnd-**

- [ ] login page for users
- [ ] Codeforces stats analyser
- [ ] Codechef stats analyser
- [ ] Spoj stats analyser
- [ ] Leetcode stats analyser
- [ ] recommended problems displayed
